# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-29 07:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import magazine.models
import tinymce.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publishDate', models.DateTimeField(default=datetime.datetime.now)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('teaser', tinymce.models.HTMLField(blank=True)),
                ('body', tinymce.models.HTMLField(blank=True)),
                ('medium', tinymce.models.HTMLField(blank=True)),
                ('size', tinymce.models.HTMLField(blank=True)),
                ('statement', tinymce.models.HTMLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('streetAddress1', models.CharField(max_length=255)),
                ('streetAddress2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('zipCode', models.CharField(max_length=255)),
                ('customerID', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('theme', models.CharField(blank=True, max_length=255, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=magazine.models.issue_upload_to)),
                ('issue', models.CharField(choices=[(b'Fall', b'Fall'), (b'Winter', b'Winter'), (b'Spring', b'Spring'), (b'Commencement', b'Commencement')], default=b'Fall', max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('streetAddress1', models.CharField(max_length=255)),
                ('streetAddress2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('zipCode', models.CharField(max_length=255)),
                ('customerID', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('purchases_json', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('issue', models.CharField(max_length=255)),
                ('year', models.IntegerField(blank=True,null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=magazine.models.get_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('streetAddress1', models.CharField(max_length=255)),
                ('streetAddress2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('zipCode', models.CharField(max_length=255)),
                ('customerID', models.CharField(max_length=255)),
                ('renew', models.BooleanField(default=False)),
                ('subscriptionType', models.CharField(choices=[(b'Three year; US', b'Three year; US'), (b'Two year; US', b'Two year; US'), (b'One year; US', b'One year; US'), (b'Three year; non-US', b'Three year; non-US'), (b'Two year; non-US', b'Two year; non-US'), (b'One year; non-US', b'One year; non-US')], max_length=255)),
                ('time', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='magazine.Content')),
                ('photo', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=magazine.models.upload_image_to)),
            ],
            bases=('magazine.content',),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='magazine.Content')),
                ('photo', versatileimagefield.fields.VersatileImageField(upload_to=magazine.models.upload_image_to)),
            ],
            bases=('magazine.content',),
        ),
        migrations.AddField(
            model_name='content',
            name='contributors',
            field=models.ManyToManyField(to='magazine.Contributor'),
        ),
        migrations.AddField(
            model_name='content',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine.Issue'),
        ),
        migrations.AddField(
            model_name='content',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='magazine.Section'),
        ),
        migrations.AddField(
            model_name='content',
            name='tags',
            field=models.ManyToManyField(blank=True, to='magazine.Tag'),
        ),
    ]
