# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-25 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='issue',
            field=models.CharField(choices=[(b'Fall', b'Fall'), (b'Winter', b'Winter'), (b'Spring', b'Spring'), (b'Commencement', b'Commencement')], default=b'Fall', max_length=255),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
